#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: autogen
#
Name     : libass
Version  : 0.17.1
Release  : 7
URL      : https://github.com/libass/libass/archive/0.17.1/libass-0.17.1.tar.gz
Source0  : https://github.com/libass/libass/archive/0.17.1/libass-0.17.1.tar.gz
Summary  : LibASS is an SSA/ASS subtitles rendering library
Group    : Development/Tools
License  : ISC
Requires: libass-lib = %{version}-%{release}
Requires: libass-license = %{version}-%{release}
BuildRequires : nasm-bin
BuildRequires : pkgconfig(fontconfig)
BuildRequires : pkgconfig(freetype2)
BuildRequires : pkgconfig(fribidi)
BuildRequires : pkgconfig(harfbuzz)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(libunibreak)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
[![Build status](https://github.com/libass/libass/actions/workflows/ghci.yml/badge.svg?branch=master&event=push)](https://github.com/libass/libass/actions/workflows/ghci.yml?query=branch%3Amaster+event%3Apush)

%package dev
Summary: dev components for the libass package.
Group: Development
Requires: libass-lib = %{version}-%{release}
Provides: libass-devel = %{version}-%{release}
Requires: libass = %{version}-%{release}

%description dev
dev components for the libass package.


%package lib
Summary: lib components for the libass package.
Group: Libraries
Requires: libass-license = %{version}-%{release}

%description lib
lib components for the libass package.


%package license
Summary: license components for the libass package.
Group: Default

%description license
license components for the libass package.


%prep
%setup -q -n libass-0.17.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1679603800
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1679603800
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libass
cp %{_builddir}/libass-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libass/7b715718a08e1da65de75f83882b562e1b97b904 || :
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/ass/ass.h
/usr/include/ass/ass_types.h
/usr/lib64/libass.so
/usr/lib64/pkgconfig/libass.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libass.so.9
/usr/lib64/libass.so.9.2.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libass/7b715718a08e1da65de75f83882b562e1b97b904
